### ISSUE TITLE
"Exclude Tabs from Acquisition" function breaks tabs

### ISSUE THREAD

**Issue by kim319** [Novynn/acquisitionplus#15] opened 2015-10-27 20:10 UTC
I used the regex, ^\D to hide all tabs that do not start with a number. It excluded all the tabs correctly but now the items that are actually in the tabs that are left are all completely incorrect. They are showing items that are the tabs that are excluded for some reason.

![croppercapture 10](https://cloud.githubusercontent.com/assets/15349853/10771089/e1df4470-7cbc-11e5-9072-f00ee50a9599.png)

**Comment by Novynn** [comment] 2015-10-28 00:52
Duplicate of #11.

**Closed as completed by Novynn** 2015-10-28 00:52 UTC
Labels: duplicate
